name: Build Vite site (gh-pages)

on:
  push:
    branches:
      - Cours/master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: siteweb/lessionApp
        run: npm ci

      - name: Build Vite project
        working-directory: siteweb/lessionApp
        run: npm run build
      
      - name: Deploy onto gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: siteweb/lessionApp/dist
